 language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
deploy:
  provider: heroku
  app: money-jars
  api_key:
    secure: p29q3UDJpHgYJ5qRCcideN1Jrd6+7JKvYWM0QOjoecMrgUSsieh+bcSVTbikZ9OSvnn55a+D0VV50xEwkLtD6XbXClV1UL2akuX2ksqJvUrpZizsoE+aOTXJpYOSMm9VM4I6MIldhjsf8U7guSRPeMHGtjubuFXgy3RBfClfvsxgThNL31m+co1RL36Y2eKiQg+6u9xqdpX+7YnHBRUo/UNfIqYj7nPLpNk9w8GkFjguuHrCjl9of9705zpkoYNQZa6ocoSq3EOdqkHZW2+Y4h5z0tI6OclkMRSP7u9mXL60gSXFurQzQgQpFxSKByBGYtQGUg2akrEJDTWmPZUjSLducz3qWVuMeo/jpfztPI3uM3/Yx6oeSxE1ee0du7WZt4AQVbcFfHsAfeeWlFzHsvNd6oofCN5/Roulxd4DwGcasX+AHfaCMA1Ny2I/e7V400jFs8G3jLsFOAOmkk4FejuKJQofyazbxwn++4KzudOKNx2CAaGsuaxRVdSpBaq43mrOgZy7DE6QLLSHJSyA0FHRn4kbw+u1SUnaQIPbLXIoCAN0D9aCiI6/W41+PR+2ROOPgc10SKmo9vhHP0yrWWUpF1dfi9qpJmlHPDCkrvznnTq8g/hG2VTJlYR/QmDbL8oWlQ1qMguBxskqyF2EEsEYeJ0Assit3BQo6WoWMs8=
  on:
    repo: Carenelizabeth/money-jars-client